name: native-build
on:
  push:
    branches:
      - main

jobs:
  run:
    name: Run 'spring-native-graal'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Run 'native-build
        run: mvn -Pnative package
      # TODO: copy the native image to the /build directory 
