name: native-build
on:
  push:
    branches:
      - main
env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  
jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Add secrets
        run: |
          ls
          sed -i "s/CLIENT_ID/${{ secrets.CLIENT_ID }}/g" Java\src\main\resources\application.properties
          sed -i "s/CLIENT_SECRET/${{ secrets.CLIENT_SECRET }}/g" Java\src\main\resources\application.properties
          cat Java\src\main\resources\application.properties
      - name: Run 'native-build
        run: | 
          cd Java 
          mvn package -DskipTests
          native-image -jar target\beanfarm-0.0.1-SNAPSHOT.jar  beanfarmLocal
      - name: create artifact
        uses: actions/upload-artifact@v2
        with: 
          name: beanfarm-client-${{ matrix.os }}
          path: D:\a\client\client\Java\target\beanfarm*
      # TODO: copy the native image to the /build directory 
