name: native-build
on:
  push:
    branches:
      - main

jobs:
  run:
    name: Run 'spring-native-graal'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Run 'native-build
        run: | 
          cd Java 
          mvn -Pnative native:compile -DskipTests
              - name: Step 3 - Use the Upload Artifact GitHub Action
      - name: create artifact
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: /home/runner/work/client/client/Java/target/beanfarm
      # TODO: copy the native image to the /build directory 
