#Thu Mar 07 06:19:57 UTC 2024
micronaut:
  application:
    name: beanfarm

beanfarm:
  auth:
    client:
      url: https://accounts.google.com/
      clientId: ${CLIENT_ID}
      scope: profile
      secret: ${CLIENT_SECRET}
    server:
      host: localhost
      port: 8081
      context: /auth
      redirectUri: "http://${beanfarm.auth.server.host}:${beanfarm.auth.server.port}${beanfarm.auth.server.context}"
      timeout: 60